[[headers]]
  for = "/*"
  [headers.values]
    # Protect against clickjacking
    X-Frame-Options = "DENY"
    
    # Prevent browsers from performing MIME type sniffing
    X-Content-Type-Options = "nosniff"
    
    # Enable cross-site scripting filter
    X-XSS-Protection = "1; mode=block"
    
    # Control how much information the browser includes with navigation requests
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Control which features and APIs can be used in the browser
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=(), interest-cohort=()"
    
    # Enable strict SSL
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    
    # Content Security Policy
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdnjs.cloudflare.com;
      style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com;
      img-src 'self' data: https:;
      font-src 'self' https://cdnjs.cloudflare.com;
      connect-src 'self';
      media-src 'self';
      object-src 'none';
      frame-src 'none';
      frame-ancestors 'none';
      form-action 'self';
      base-uri 'self';
      upgrade-insecure-requests;"""

# Redirect all traffic to HTTPS
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

# Enable brotli compression
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true